"""Add storage_date and save_time fields to vaccine model

Revision ID: 07c4d0c2526a
Revises: 367eeed7e629
Create Date: 2026-01-14 10:27:17.320552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c4d0c2526a'
down_revision = '367eeed7e629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vaccines', ['vaccine_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('vaccines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('save_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccines', schema=None) as batch_op:
        batch_op.drop_column('save_time')
        batch_op.drop_column('storage_date')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
