"""Add rejection_reason field to Appointment

Revision ID: 367eeed7e629
Revises: ba5ec9d0d60a
Create Date: 2026-01-10 14:25:50.581805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367eeed7e629'
down_revision = 'ba5ec9d0d60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'vaccines', ['vaccine_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
