"""Add appointment reason and last vaccination date fields

Revision ID: ba5ec9d0d60a
Revises: e09411c09077
Create Date: 2026-01-10 11:44:02.617938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5ec9d0d60a'
down_revision = 'e09411c09077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('last_vaccination_date', sa.Date(), nullable=True))
        batch_op.create_foreign_key(None, 'vaccines', ['vaccine_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_vaccination_date')
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
