"""Add user profile fields

Revision ID: e09411c09077
Revises: 
Create Date: 2026-01-09 23:51:48.568908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09411c09077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vaccines', ['vaccine_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('id_card', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('has_allergy', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contraindications', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['id_card'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('contraindications')
        batch_op.drop_column('has_allergy')
        batch_op.drop_column('address')
        batch_op.drop_column('id_card')
        batch_op.drop_column('gender')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
